a = input ("Digite algo: ")
print ("O tip primitivo desse valor é", type(a))
print ("Só tem espaços?", a.isspace())
print ("É um numero?", a.isnumeric())
print ("É alfabetico ", a.isalpha())
print ("É alfanumerico? ", a.isalnum())
print ("Esta maiusculas? ", a.isupper())
print ("Esta minusculas? ", a.islower())
print ("Está capitalizada? ", a.istitle())